class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'extract1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list1'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone1'
        self.WatchCommand = 'youtube1'
        self.TarWatchCommand = 'playlist1'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo'

BotCommands = _BotCommands()
