class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'filesmirror'
        self.UnzipMirrorCommand = 'extract'
        self.TarMirrorCommand = 'tarmirror5'
        self.CancelMirror = 'cancel5'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list5'
        self.StatusCommand = 'status5'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart5'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help5'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone5'
        self.WatchCommand = 'youtube'
        self.TarWatchCommand = 'playlist'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo'

BotCommands = _BotCommands()
